version: "3"

services:

  fleetman-webapp:
    image: netof/fleetman-webapp
    networks:
      - fleetman-network
    ports:
      - 8080:8080

  database:
    image: mysql:5
    networks:
      - fleetman-network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=fleetman

networks:
  fleetman-network: